# --------------- Credits ---------------
# File:   kitty.conf
# Author: Gabriel Caussi
# Source: https://github.com/gabrielcaussi/.dotfiles/

# --------------- Kitty Settings ---------------

# Set Theme
include theme.conf

# Font settings
font_family Fira Code
font_size 10

# Cursor settings (1 = enable)
cursor_blink_interval 0

