background            #1C1A1C
foreground            #EFEFEF

selection_foreground  #FFFFFF
selection_background  #365883

cursor                #FFFFFF

color0                #545454
color1                #FF5454
color2                #54FF54
color3                #FFFF54
color4                #5454FF
color5                #FF54FF
color6                #54FFFF
color7                #FFFFFF

color8                #000000
color9                #AA0000
color10               #00AA00
color11               #AAAA00
color12               #0000AA
color13               #AA00AA
color14               #00AAAA
color15               #AAAAAA
