#!/bin/sh

# Start sxhkd
sxhkd &

# Start flameshot
flameshot &

# Polybar
sh ~/.config/polybar/launch.sh &

# Wallpaper
feh --bg-fill ~/Pictures/wallpaper.jpg &

# Name of workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Window border
bspc config focused_border_color "#D65D0E"
bspc config border_width          2
bspc config window_gap            0
bspc config split_ratio           0.5

# Window rules
bspc config focus_follows_pointer true

# Open in specific workspaces
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a kitty desktop='^2' follow=on
bspc rule -a code desktop='^3' follow=on
bspc rule -a nemo desktop='^4' follow=on
bspc rule -a vlc desktop='^5' follow=on
bspc rule -a Free Download Manager desktop='^6' follow=on
bspc rule -a TelegramDesktop desktop='^8' follow=on
bspc rule -a discord desktop='^9' follow=on
bspc rule -a spotify desktop='^10' follow=on

# Window state configs
bspc rule -a Lxappearance state=floating focus=on

# Mouse settings
xsetroot -cursor_name left_ptr
xinput set-prop "ELAN0501:01 04F3:3060" "libinput Natural Scrolling Enabled" 1
xinput set-prop "ELAN0501:01 04F3:3060" "libinput Click Method Enabled" 0 1
xinput set-prop "ELAN0501:01 04F3:3060" "libinput Disable While Typing Enabled" 0

# Keyboard settings
#setxkbmap -layout br,us -option grp:shift_caps_toggle
setxkbmap -layout br thinkpad -option grp:shift_caps_toggle

# Vim scape (Caps Lock = Esc)
setxkbmap -option caps:swapescape &

