#!/bin/sh

# Services that start with bspwm
sxhkd &

# Background
feh --bg-fill ~/Pictures/wallpaper.jpg &

# Polybar
sh ~/.config/polybar/launch.sh &

# Start flameshot
flameshot &

# Name of workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Border
bspc config focused_border_color "#009185"
bspc config normal_border_color  "#555555"
bspc config border_width          3
bspc config window_gap           15
bspc config split_ratio         0.5

bspc config focus_follows_pointer true

# Mouse
xsetroot -cursor_name left_ptr
xinput set-prop "ELAN0501:01 04F3:3060" "libinput Natural Scrolling Enabled" 1
xinput set-prop "ELAN0501:01 04F3:3060" "libinput Click Method Enabled" 0 1
xinput set-prop "ELAN0501:01 04F3:3060" "libinput Disable While Typing Enabled" 0

# Keyboard
setxkbmap -layout br,us -option grp:shift_caps_toggle  

# Vim Scape
setxkbmap -option caps:swapescape &

# Files
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
