# --------------- Credits ---------------
# File:   .tmux.conf
# Author: Gabriel Caussi
# Source: https://github.com/gabrielcaussi/.dotfiles/

# --------------- Basic Settings ---------------

# Changes prefix to Ctrl+a
set -g prefix C-a
unbind-key C-b

# Terminal type
set -g default-terminal "screen-256color"

# Enables mouse events
set -g mouse on

# Starts windows numbers at 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when closing one
set-option -g renumber-windows on

# Set color at Status Bar
set -g status-bg black
set -g status-fg white

# Status Bar settings
set -g status-interval 1
set -g window-status-format '#I:#(pwd="#{pane_current_path}"; echo ${pwd####*/})'
set -g window-status-current-format '[#I:#(pwd="#{pane_current_path}"; echo ${pwd####*/})]'
set -g status-right-length 120
set -g status-right '#(date +"%b %_d %H:%M") | #(whoami)@#(hostname -s) '

# --------------- Shortcuts ---------------

bind v split-window -h -c "#{pane_current_path}"  # split vertically
bind h split-window -v -c "#{pane_current_path}"  # split horizontally
bind n new-window                                 # open new window
bind x kill-pane                                  # kill pane without confirmation
bind k kill-window                                # kill window
bind q kill-session                               # kill session
bind r source-file ~/.tmux.conf                   # reload tmux config
bind t select-layout tiled                        # tiled layout

# Red status bar when on SSH connection
if-shell 'test "$SSH_CONNECTION"' 'set -g status-bg red'

